/* POOF - site behavior
   Edit this file directly (it is not generated by generate.py). */

(function () {
  "use strict";

  /* ---- scroll reveal ---------------------------------------------------
     Applied to section headers and cards. Respects reduced-motion via CSS. */
  var targets = document.querySelectorAll(".sec__h, .card, .step, .routes li, .starter");
  if ("IntersectionObserver" in window && targets.length) {
    Array.prototype.forEach.call(targets, function (el) { el.classList.add("reveal"); });
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add("in");
          io.unobserve(entry.target);
        }
      });
    }, { rootMargin: "0px 0px -60px 0px", threshold: 0.08 });
    Array.prototype.forEach.call(targets, function (el) { io.observe(el); });
  }

  /* ---- carry the hero textarea into the estimate form ---- */
  var params = new URLSearchParams(window.location.search);
  var carried = params.get("q");
  var itemsField = document.getElementById("items");
  if (carried && itemsField) {
    itemsField.value = carried;
  }

  /* ---- estimate form ---------------------------------------------------
     BACKEND NOT CONNECTED YET.

     The estimator needs a server-side endpoint that holds the Anthropic API
     key (a Cloudflare Worker or similar). An API key cannot live in this
     file - anything here is public and would be scraped.

     Until that endpoint exists, this form does not submit anywhere. It tells
     the visitor plainly and points them at the phone number rather than
     silently failing or pretending to have sent something.

     To wire it up later, replace the handler body with a fetch() to the
     Worker URL. */
  var form = document.getElementById("estimate-form");
  var status = document.getElementById("form-status");

  if (form && status) {
    form.addEventListener("submit", function (e) {
      e.preventDefault();

      var email = document.getElementById("email");
      var items = document.getElementById("items");

      if (!items.value.trim()) {
        status.textContent = "Add a short description of what needs to go, then try again.";
        items.focus();
        return;
      }
      if (!email.value.trim() || email.value.indexOf("@") === -1) {
        status.textContent = "Add an email address so we know where to send the estimate.";
        email.focus();
        return;
      }

      status.innerHTML =
        "<strong>The instant estimator isn't switched on yet.</strong><br>" +
        "This form isn't sending anywhere while we finish building it, so nothing " +
        "was submitted. Call or text us instead, photos included, and we'll price " +
        "it in a couple of minutes.";
    });
  }
})();
